/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lenovo
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewCastVote = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtViewVote = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 23, 286, 45));

        btnViewCastVote.setBackground(new java.awt.Color(255, 0, 0));
        btnViewCastVote.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnViewCastVote.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCastVote.setText("View Cast Vote");
        btnViewCastVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCastVoteActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewCastVote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 47));

        txtViewVote.setColumns(20);
        txtViewVote.setRows(5);
        jScrollPane1.setViewportView(txtViewVote);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 340, 260));

        btnBack.setBackground(new java.awt.Color(102, 255, 51));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 23, 89, 37));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/online.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginPageAdmin frm = new LoginPageAdmin();
        frm.setVisible(true);
        frm.setBounds(400,200,500,400);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewCastVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCastVoteActionPerformed
        FileReader reader = null;
        int x = 0, y = 0, z = 0,aa=0,bb=0,cc=0,dd=0,ee=0;
        String a = "Awami League";
        String b = "BNP";
        String c = "National Party";
        String d = "Male";
        String e = "Female";
        String f = "Centre A";
        String g = "Centre B";
        String h = "Centre C";
        try {
            reader = new FileReader("D:\\Online voting System\\CastVote.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            BufferedReader bufferedReader = new BufferedReader(reader);
            
            String line = "";
            
        try {
            while((line = bufferedReader.readLine()) != null){
                String [] singleLine = line.split(",");
                if(singleLine[0].isEmpty() == true)continue;
                if(singleLine[0].isEmpty() == true){
                    continue;
                }
                if(singleLine[0].equals(a) == true){
                    x++;
                }
                else if(singleLine[0].equals(b) == true){
                    y++;
                }
                else if(singleLine[0].equals(c) == true){
                    z++;
                }
                if(singleLine[2].equals(d) == true){
                    aa++;
                }
                else if(singleLine[2].equals(e) == true){
                    bb++;
                }
                if(singleLine[3].equals(f) == true){
                    cc++;
                }
                else if(singleLine[3].equals(g) == true){
                    dd++;
                }
                else if(singleLine[3].equals(h) == true){
                    ee++;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        String found = "The Party Cast Vote : "+"\n";
        found = found + "Awami League : " + String.valueOf(x) + "\n";
        found = found + "BNP : " + String.valueOf(y) + "\n";
        found = found + "National Party : " + String.valueOf(z) + "\n";
        
        found = found + "Gender Cast Vote : "+"\n";
        found = found + "Male : " + String.valueOf(aa) + "\n";
        found = found + "Female : " + String.valueOf(bb) + "\n";
        
        found = found + "Centre Cast Vote : "+"\n";
        found = found + "Centre A : " + String.valueOf(cc) + "\n";
        found = found + "Centre B : " + String.valueOf(dd) + "\n";
        found = found + "Centre C : " + String.valueOf(ee) + "\n";
        txtViewVote.setText(found);
    }//GEN-LAST:event_btnViewCastVoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewCastVote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtViewVote;
    // End of variables declaration//GEN-END:variables
}
